GET http://localhost:3001/api/blogs

###
POST http://localhost:3001/api/blogs
Content-Type : application/json

{
    "title": "testiblogi",
    "author": "minävain",
    "url": "localhost:3001",
    "likes": 5
}
###
PUT http://localhost:3001/api/blogs/63c6ca1fb0152ad35a59b7c9
Content-Type: application/json

{
    "likes": 10
}